### ISSUE TITLE
Klonowanie przedmiotów

### ISSUE THREAD

**Issue by szymonkrygier** [Diorite/Diorite#17]
Wiem, że aktualnie pracujecie nad tym i spodziewam się, że o tym wiecie jednak mimo wszystko dodam.

Jeżeli na pasku wrzucimy jakiś blok, powiedzmy drewno i taki sam blok do eq i następnie wciśniemy shifta i lewy przycisk myszki to nie dość, że z jednego itemka powieli się on na dwa (Ten w ekwipunku) to dodatkowo pojawi się drugi obok. Możemy robić tak w nieskończoność. :)

@ Edit

Zapoznam się jeszcze troche z source code Diorite i będę wrzucał issues od razu z gotowym poprawionym kodem i tak dalej, żeby wam trochę pomóc.

**Comment by GotoFinal** [comment]
To chyba tylko bug graficzny (komenda /dev:inv odświeża EQ, możesz nią testować czy itemki są prawdziwe), ale wynika z innego buga, a dokładniej z tym że zapomniałem dodać equals/hashcode do meta daty itemkow i samego nbt.

Zaraz się to poprawi.

**Comment by GotoFinal** [comment]
Poszła nowa wersja, itemki powinny już poprawnie się stackować. 
http://ci.diorite.org/job/Diorite/73/
