### ISSUE TITLE
Enable jenkins maven repository

### ISSUE THREAD

**Issue by sgdc3** [Diorite/Diorite#20]
So we can start developing amazing addons! :)

**Comment by GotoFinal** [comment]
I think that I don't understand what you mean, as we have maven repo + nexus:
http://diorite.org/nexus/#view-repositories;snapshots~browsestorage

```
<repository>
    <id>diorite-snapshots</id>
    <url>http://diorite.org/nexus/content/repositories/snapshots/</url>
</repository>
```

```
<dependency>
  <groupId>org.diorite</groupId>
  <artifactId>diorite-api</artifactId>
  <version>indev-0.0.1-SNAPSHOT</version>
</dependency>
```

**Comment by sgdc3** [comment]
Ah ok, I didn't notice that. I'm used to use standard jenkins repos (auto generated ones) ;)

**Comment by Arnuh** [comment]
Pretty sure latest is 0.0.2 btw

**Comment by GotoFinal** [comment]
@Borlea 
this is just old issue, it was 0.1 then

**Comment by Arnuh** [comment]
Ahh mb, didn't read date.. just looked at the "closed" time
