### ISSUE TITLE
Registering events?

### ISSUE THREAD

**Issue by Arnuh** [Diorite/Diorite#30]
About a month ago I looked pretty much everywhere on how to 'register' an event and found nothing.. Wondering if I'm just looking in the wrong places.

**Comment by GotoFinal** [comment]
Sorry for time, about problem...

All event/pipeline system will be changed when I find time for that, and I never finished API for current one.
I need change them as Pipelines are great to control low/middle level stuff, like some actions on player join, loading server, where you may want add some advanced logic in valid place, but they are useless for more advanced stuff, like inventory actions where we should have some simple way to determine how items were moved without manually tracking all clicks...

So for now you can play with `EventType.getByEvent(PlayerJoinEvent.class).getPipeline()` but it will be changed/removed later anyway.

**Comment by Arnuh** [comment]
Thanks for giving me something to look into, I would love to help with this but you are doing some things I have not quite looked into yet.

**Comment by GotoFinal** [comment]
@Borlea You mean some code or idea that you can't understand yet? I can try explain it to you, or maybe you just found something that also is only temporary.

**Comment by Arnuh** [comment]
@GotoFinal 
I meant with the whole pipeline system and changing it.

After a bit of a break from working on diorite stuff I got it working with getting the event pipline and adding a class that implements EventPipelineHandler.

I do have another question though, is the string argument just for other plugins to access it? or am I missing something

**Comment by GotoFinal** [comment]
@Borlea Yep, it is for other plugins/debug/timings, so you can also remove/replace default diorite handlers with own one.
You can also use names to add new element directly after or before selected handler.

**Comment by GotoFinal** [comment]
#38
