### ISSUE TITLE
Block is not null when stack size is < 1

### ISSUE THREAD

**Issue by mastercoms** [Diorite/Diorite#33]
This will allow negative stack sizes when placing blocks, and you can give items of negative amount using the item command.

**Comment by GotoFinal** [comment]
I don't see anything really wrong with ability to get negative items, but it should not be possible to place blocks with negative stack, and maybe command should ignore -1 too.

**Comment by mastercoms** [comment]
It works for any negative value, not just -1. Also, what would the use of negative blocks be?

**Comment by GotoFinal** [comment]
@mastercoms none for vanilla, but plugins may want use it for some points, indicate infinite stack or something. But I will add something to make sure that players will not place blocks with amount < 1.
But later, I need to change some other stuff before that.
