### ISSUE TITLE
Diorite - ideas behind whole project.

### ISSUE THREAD

**Issue by GotoFinal** [Diorite/Diorite#41]
# **You can write own ideas or questions in this issue.**

Diorite is just new project for Minecraft server, like we have spigot on many others less or more advanced ones.
So.. if we already have spigot and sponge, why choose Diorite? Main idea behind diorite is create server software made for plugins (and maybe mods in the future), it isn't made to be just clone of vanilla with some API, it will be whole engine for Minecraft plugins.
# **Diorite - Server made for developers.**
## Our target

Also, diorite isn't based on NMS code like spigot, and don't have tons of weird bytecode manipulations that affect packet manipulation and reflections like sponge/forge.
There are 2 main targets of diorite:
### Multi-threaded

Minecraft isn't prepared for multiple threads so this may be very hard, but we still want to try. Whole server will be made of `TickRegions`, one tick region can be few smaller maps, or one small region made of 32x32 chunks. (I want keep smallest possible region to be equals to single file, that will make saving map a lot easier)
This may cause many problems with creating API and implementation, as we need be more friendly for multiple threads accessing some fields, but for most changes plugins should use task, every task can be synchronized to given entity/chunk/etc -> it will execute in this same thread as entity was ticked.
Biggest problem will be with primitive maps, as currently we don't have any concurrent versions of them.
### Plugins

We want allow developers to create advanced plugins without need to use reflections, editing diorite code etc, even if they want do some unsafe stuff that may break.
You want add new Enchantment? no problem, just remember that client can't display them on item so you need create own lore. (See #39 for lore system idea)
You want add new block that looks like other one but have own save id and properties? No problem, you can.
New entity, based on exiting one? Sure, you will be able to do this too.
You want to change how some entity works? no problem, you can use its pipeline to change how it works, or just add/remove some of pathfinders.
### Code layers

After some playing around code, I decided that more important parts of diorite will be made of 3 layers:

3 layers mode, for all advanced stuff like entites etc:
- API - Where most of features can be used, it will be pretty powerful, but may be not everything needed to create some very advanced RPG servers or weird minigame stuff. But you will be able 
- CoreAPI - Extension of API that contains all needed implementation side methods, ONLY classes from CoreAPI are used in rest of Dirotie code.
- Implementation - Lowest layer, classes from that layer are only used by other Implementation classes of this same type, like Entity implementation class is only used from other entities implementation classes - plugin may override whole entity system without need to edit any diorite code.
  See entity code for example: https://github.com/Diorite/Diorite/tree/master/diorite-core/src/main/java/org/diorite/impl/entity

Some other simple stuff will only have API layer, like `InventorySlot`, every plugin can just implement that class and pass it directly to any method, and it will be never cast to any implementation type.
Implementation code may only contains basic implementations of this interface, like `InventorySlot` class used by chests, but diorite will never cast any slot in chest to ChestSlot.
### Everything is API

What this means? Like in bukkit you were unable to affect default world generator, as it was on NMS side, you must add own one, in diorite default generator will be accessible from API too, with this same API methods as every other generator.
In Diorite everything is made of API and some implementations, there is no hidden parts.
### Diorite site

We also need some good site for diorite that will make everything easier, place to upload plugins etc. Currently main person that play around site is @NorthPL 
- Site should contains plugin catalog where every plugin contains some tags, like `#fun #guilds` server admins will use them to find some kind of plugin that they need.
- There should be 2 types of plugins, every new plugin is "untrusted" and after check it will appear in normal repository. I have no idea how checking will look, maybe it will be made by some java program, that will look for some unsafe stuff, like reflections, command invokes etc, and it will list all unsafe stuff and give "safety rate", plugins with low rate will be reviewed manually, but all found "issues" in untested (by site mods) plugins will be listed in plugin download, so admins can see if plugins looks safe.
- **ALL plugins should be added to diorite maven repository.**
- If we will want support paid plugins too, repository should be protected or just disabled for them.
## Client

We also want create Diorite client - DioritOS, that will have special features when used with diorite server, both diorite server and client will be vanilla compatible, but together they will be able to do much more, like:
- Adding simple blocks at runtime or login time, with own textures, properties etc.
- Better support for custom crafting recipes, DioritOS unlike vanilla, will not process recipes on client side, it will wait for server reply
- This same for custom entities. 
- And GUIs

But what will be not supported?
We don't want support sending mods from server to client or allow to any way of executing code on client computer, DioritOS should still be safe, maybe we will create some Mod repository, and server will be able to send name and version of given mod and then client will download them, mods in repository should be tested for any code that can cause damage for client.
# **You can write own ideas or questions in this issue.**

**Comment by phase** [comment]
Instead of DioritOS, can we call it DoritOS?

**Comment by artur9010** [comment]
@phase
![doritos_fix_package_detail_01](https://cloud.githubusercontent.com/assets/4835677/13366436/77e9377c-dcdb-11e5-80fa-9905a6fe8a9c.jpg)

( ͡° ͜ʖ ͡°)

**Comment by ghost** [comment]
How Tickregions will work on borders? When entity from one region hit entity in other region

**Comment by GotoFinal** [comment]
@ensirius as they aren't ready yet, I can't really tell anything special about that.
I hope that with small usage of few concurrent collections we will be able to skip synchronization here, and just allow them to fight, diorite don't need work exactly like vanilla, this isn't our target, so as long as that will not crash the server or cause any bugs, dupes, etc, it will be fine.
In java 8 they really improved concurrent classes, especially stuff like concurrent hashmaps that no longer need few copies of data to work.

**Comment by gizmocodes** [comment]
Umm... on the site it says you want to support other mods (Forge is what I remember seeing), but what about the most-likely Bukkit replacement [Sponge](https://spongepowered.org)?

**Comment by GotoFinal** [comment]
@GizmoCodes IDK, maybe someday. Supporting mods/forge is still additional idea, we don't know if we will support it at the end, for sure we want support at least some simple bukkit plugins.
