### ISSUE TITLE
Wyrzucanie przedmiotów nie działa jak powinno.

### ISSUE THREAD

**Issue by artur9010** [Diorite/Diorite#5]
Wyrzucanie przedmiotów (Q) zawsze wyrzuca item w jednym kierunku.

**Comment by GotoFinal** [comment]
Aktualnie po prostu nie ma systemu wyrzucania itemków i są one po prostu setowane 2 kratki od gracza w jakimś tam kierunku.

**Comment by GotoFinal** [comment]
test

**Comment by GotoFinal** [comment]
test

**Comment by GotoFinal** [comment]
test

**Comment by mibac138** [comment]
Wydaje mi się, że już to zostało naprawione.
