### ISSUE TITLE
Niektóre drzewa są niepoprawnie generowane.

### ISSUE THREAD

**Issue by artur9010** [Diorite/Diorite#6]
Niektóre drzewa są generowane do połowy.
https://imgur.com/DGyjkdR

**Comment by GotoFinal** [comment]
Generują się całe, ale widzisz tylko połowę, bug powstaje kiedy generują się nowe chunki, generuje się nowy chunk z drzewem na krawędzi, i część jego liści znajduje się na chunku który już jest wygenerowany i którego już widzisz, ale te zmiany nie są do ciebie wysyłane, po relogu drzewo powinno być całe.

Znany bug, zostanie on naprawiony, ale nie teraz, bo przed tym musi powstać odpowiedni system.

PS: pisz te bugi po ang następnym razem jednak... :D
