### ISSUE TITLE
Idea for Diorite Launcher

### ISSUE THREAD

**Issue by GrumpyBear57** [Diorite/Diorite#89]
So I have no idea if this is the route you'd be willing to take, but I have no other way of contributing because I suck at Java, so this is my best shot. 

I know how to make basic GUI Apps with [Electron](http://electron.atom.io/) (Node.js), so while it wouldn't be Java (at first at least, it could eventually become Java instead of JavaScript/HTML/CSS), it would be something extremely easy to make and maintain (No idea how hard it is to make a GUI Java app though, so it might actually be easier).

Initially all it would have to do is run a shell command to launch the jar file (which I assume is how the client will be distributed, correct me if I'm wrong), and a basic page to edit the configs. The last three points on [the Project.md file](https://github.com/Diorite/Diorite/blob/master/project/Project.md#diorite-launcher) is where I see it becoming a little more involved to create, but *should* still be easy enough to accomplish. 

I'd love to see this project become a reality as quick as possible, and I can think of no other way for me to help that happen other than contributing (I saw donations as another option, to give more incentive, but I don't have money to donate). But as I previously mentioned, I'm terrible at Java (I need step by step instructions to get anything done :P). I completely understand if this is not the route you want to go, and wish to have a fully Java environment, this was just the easiest way I saw that would allow me to contribute in a manner that isn't just correcting small grammatical errors :P

**Comment by GotoFinal** [comment]
This can be a good thing for client, but for now client don't exist, and I would prefer to use Java anyway.
Launcher for server is a different thing, main idea of it is to download dependencies, plugins etc, you know, most of servers use only CLI, so launcher graphic mode will be optional for server, and it must be in Java to provide access to all diorite plugins and their classes.
So this isn't good idea for now, also (for client) I want to create small native launcher that will download Java first, so it will be better to keep rest of stuff in Java to minimalize size.

**Comment by GrumpyBear57** [comment]
Alright fair enough. I guess I'll just have to learn Java if I want to contribute then.
