### ISSUE TITLE
Źle działające "pobieranie klocków"

### ISSUE THREAD

**Issue by instans** [Diorite/Diorite#9]
Podczas używania opcji Pick Block (przycisk scrolla, do pobierania klocków na creative) wywala z serwera, z powodem disconnected/połączenie zerwane przez hosta.

**Comment by GotoFinal** [comment]
po 1: EQ creative nie jest jeszcze gotowe.
po 2: pick block nie jest jeszcze w pełni zaimplementowany.

**Comment by instans** [comment]
postaram sie tutaj pisac wszystko co znajde z błędów, bawie sie aktualnie na serwerze róznymi opcjami :P

**Comment by GotoFinal** [comment]
większość takich błędów to ja znam, tylko po prostu jest tak dużo do zrobienia, ze nie wiadomo od czego zacząć.
