### ISSUE TITLE
Inspections (just a question)

### ISSUE THREAD

**Issue by ghost** [Diorite/Diorite#96]
Hey, is it possible to get/download from somewhere not only code style but inspections used in Diorite too?

**Comment by GotoFinal** [comment]
Not really, I din't have them due to failure of my SSD and I didn't have backup for such data, but there isn't anything special in them tho, why you even need them?

**Comment by ghost** [comment]
I was just curious about it. In older repo of Diorite you actually did upload inspections so I just thought you would post new inspections here like the code style and other things too because as I can see they have changed since last time.

**Comment by GotoFinal** [comment]
Just keep it clean ¯\_(ツ)_/¯

**Comment by ghost** [comment]
Okay, thanks for the answer. :>
