### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ghost** [Diorite/Diorite#98]
Hi there! I'd like to know whether or not this project is still active or managed by someone. I'm a maintainer of [Impulse](https://github.com/impulsecl/impulse) and I'm currently implementing plugin support for all the servers I can find.

An answer would be much appreciated.
Sincerely, ShadowAria.

**Comment by GotoFinal** [comment]
Hi, and sadly nope.

**Comment by MrGregorix** [comment]
Yes, it isn't.

**Comment by dzikoysk** [comment]
Yes
